// packages/searchbox-vue/src/components/Highlighted.vue
<script setup lang="ts">
import { highlight } from '@zbsearch/searchbox-core'
import { computed } from 'vue'

const props = defineProps<{ text: string; query: string }>()

const segments = computed(() => highlight(props.text, props.query))
</script>

<template>
  <span>
    <template v-for="(segment, index) in segments" :key="index">
      <mark v-if="segment.match" class="zbs-searchbox__mark zbsearch-highlight">{{ segment.text }}</mark>
      <template v-else>{{ segment.text }}</template>
    </template>
  </span>
</template>

// packages/searchbox-react/src/components/Highlighted.tsx
import { Fragment } from 'react'
import { highlight } from '@zbsearch/searchbox-core'

export interface HighlightedProps {
  text: string
  query: string
  className?: string
}

export function Highlighted({ text, query, className }: HighlightedProps) {
  const segments = highlight(text, query)

  return (
    <span className={className}>
      {segments.map((segment, index) =>
        segment.match ? (
          <mark key={index} className="zbs-searchbox__mark zbsearch-highlight">
            {segment.text}
          </mark>
        ) : (
          <Fragment key={index}>{segment.text}</Fragment>
        )
      )}
    </span>
  )
}
