// packages/searchbox-vue/src/components/SearchButton.vue
<script setup lang="ts">
import { useIsApplePlatform } from '../composables/useHotkeys.js'
import { SearchIcon } from './icons.js'

withDefaults(
  defineProps<{
    label?: string
    ariaLabel?: string
    shortcut?: boolean
  }>(),
  {
    label: 'Search',
    ariaLabel: 'Search (Command+K)',
    shortcut: true
  }
)

const emit = defineEmits<{ click: [] }>()

const isApple = useIsApplePlatform()
</script>

<template>
  <button
    type="button"
    class="zbs-search-button"
    :aria-label="ariaLabel"
    data-testid="zbs-search-button"
    @click="emit('click')"
  >
    <span class="zbs-search-button__icon" aria-hidden="true">
      <SearchIcon />
    </span>

    <span class="zbs-search-button__label">{{ label }}</span>

    <span v-if="shortcut" class="zbs-search-button__keys" aria-hidden="true">
      <kbd class="zbs-search-button__kbd">{{ isApple ? '⌘' : 'Ctrl' }}</kbd>
      <kbd class="zbs-search-button__kbd">K</kbd>
    </span>
  </button>
</template>

// packages/searchbox-react/src/components/SearchButton.tsx
import { useIsApplePlatform } from '../hooks/useHotkeys.js'
import { SearchIcon } from './icons.js'

export interface SearchButtonProps {
  onClick: () => void
  label?: string
  ariaLabel?: string
  shortcut?: boolean
  className?: string
}

export function SearchButton({
  onClick,
  label = 'Search',
  ariaLabel = 'Search (Command+K)',
  shortcut = true,
  className
}: SearchButtonProps) {
  const isApple = useIsApplePlatform()

  return (
    <button
      type="button"
      className={className ? `zbs-search-button ${className}` : 'zbs-search-button'}
      aria-label={ariaLabel}
      data-testid="zbs-search-button"
      onClick={onClick}
    >
      <span className="zbs-search-button__icon" aria-hidden="true">
        <SearchIcon />
      </span>
      <span className="zbs-search-button__label">{label}</span>
      {shortcut ? (
        <span className="zbs-search-button__keys" aria-hidden="true">
          <kbd className="zbs-search-button__kbd">{isApple ? '⌘' : 'Ctrl'}</kbd>
          <kbd className="zbs-search-button__kbd">K</kbd>
        </span>
      ) : null}
    </button>
  )
}
